# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/chose_form_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1225, 600)
        Form.setStyleSheet("*{\n"
"    font-family:century gothic;\n"
"    font-size:24px\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("background:transparent;\n"
"")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.username_lbl = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_lbl.sizePolicy().hasHeightForWidth())
        self.username_lbl.setSizePolicy(sizePolicy)
        self.username_lbl.setStyleSheet("background:transparent;\n"
"color:#717072;\n"
"")
        self.username_lbl.setObjectName("username_lbl")
        self.gridLayout.addWidget(self.username_lbl, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(610, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 3)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 5, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.camera_lbl = QtWidgets.QLabel(self.groupBox)
        self.camera_lbl.setText("")
        self.camera_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.camera_lbl.setObjectName("camera_lbl")
        self.gridLayout_2.addWidget(self.camera_lbl, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 6)
        spacerItem1 = QtWidgets.QSpacerItem(527, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 3)
        self.logout_btn = QtWidgets.QPushButton(Form)
        self.logout_btn.setStyleSheet("color:white;\n"
"background:red;\n"
"border-radius: 15px;\n"
"\n"
"")
        self.logout_btn.setObjectName("logout_btn")
        self.gridLayout.addWidget(self.logout_btn, 2, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(464, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 4, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Username :"))
        self.username_lbl.setText(_translate("Form", "username_lbl"))
        self.label_2.setText(_translate("Form", "DRIVER SINK PROJECT"))
        self.groupBox.setTitle(_translate("Form", "CAMERA"))
        self.logout_btn.setText(_translate("Form", "SIGN OUT"))
