# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/login_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1413, 848)
        Form.setLayoutDirection(QtCore.Qt.RightToLeft)
        Form.setStyleSheet("*{\n"
"    font-family:century gothic;\n"
"    font-size:24px\n"
"}\n"
"QFrame\n"
"{\n"
"    background:rgba(0,0,0,0.8);\n"
"    border-radius:15px;\n"
"}\n"
"#Form{\n"
"background-image: url(:/newPrefix/material/photo-1553095066-5014bc7b7f2d.jfif);\n"
"}\n"
"QpushButton\n"
"{\n"
"\n"
"background:red;\n"
"border-radius: 60px;\n"
"}\n"
"QToolButton\n"
"{\n"
"\n"
"background:red;\n"
"border-radius: 60px;\n"
"}\n"
"QLabel\n"
"{\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"QpushButton\n"
"{\n"
"border-radious:15px;\n"
"}\n"
"QpushButton_2\n"
"{\n"
"color:white;\n"
"border-radius: 15px;\n"
"}\n"
"QlineEdit\n"
"{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(232, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 95, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(1014, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/forms/material/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(128, 128))
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 3, 2, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(601, 681))
        self.frame.setStyleSheet("*{\n"
"    font-family:century gothic;\n"
"    font-size:24px\n"
"}\n"
"QFrame\n"
"{\n"
"    background:rgba(0,0,0,0.8);\n"
"    border radius:15px;\n"
"}\n"
"QpushButton\n"
"{\n"
"\n"
"background:red;\n"
"border-radius: 60px;\n"
"}\n"
"QpushButton_2\n"
"{\n"
"color:white;\n"
"border-radious:15px;\n"
"}\n"
"QpushButton_2:hover\n"
"{\n"
"color:red;\n"
"border-radious:15px;\n"
"background:#49ebff;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(220, 80, 151, 81))
        self.label.setStyleSheet("*{\n"
"    font-family:century gothic;\n"
"    font-size:24px;\n"
"background:transparent;\n"
"\n"
"}")
        self.label.setObjectName("label")
        self.login_btn = QtWidgets.QPushButton(self.frame)
        self.login_btn.setGeometry(QtCore.QRect(40, 570, 531, 61))
        self.login_btn.setStyleSheet("color:white;\n"
"background:red;\n"
"border-radius: 15px;\n"
"\n"
"")
        self.login_btn.setObjectName("login_btn")
        self.username_lin = QtWidgets.QLineEdit(self.frame)
        self.username_lin.setGeometry(QtCore.QRect(60, 220, 491, 51))
        self.username_lin.setStyleSheet("background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;")
        self.username_lin.setText("")
        self.username_lin.setObjectName("username_lin")
        self.password_lin = QtWidgets.QLineEdit(self.frame)
        self.password_lin.setGeometry(QtCore.QRect(60, 380, 491, 51))
        self.password_lin.setStyleSheet("background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;")
        self.password_lin.setInputMask("")
        self.password_lin.setText("")
        self.password_lin.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lin.setObjectName("password_lin")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 180, 141, 41))
        self.label_2.setStyleSheet("background:transparent;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(60, 340, 141, 41))
        self.label_3.setStyleSheet("background:transparent;\n"
"")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.frame, 2, 1, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.toolButton.setText(_translate("Form", "..."))
        self.label.setText(_translate("Form", "LOGIN HERE"))
        self.login_btn.setText(_translate("Form", "LOGIN"))
        self.username_lin.setPlaceholderText(_translate("Form", "Username"))
        self.password_lin.setPlaceholderText(_translate("Form", "Password"))
        self.label_2.setText(_translate("Form", "Username"))
        self.label_3.setText(_translate("Form", "Password"))
import hel_rc
import icons_rc
